export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const GET_POSTS_SUCCESSFULLY = 'GET_POSTS_SUCCESSFULLY';
export const GET_ONE_POST_SUCCESSFULLY = 'GET_ONE_POST_SUCCESSFULLY';
export const LOGOUT_USER_SUCCESSFULLY = 'LOGOUT_USER_SUCCESSFULLY';